### ISSUE TITLE
Run as a service

### ISSUE THREAD

**Issue by taniman** [taniman/gunbotproxycommunity#1]
We would like to be able to run the jar as a service. Maybe this could help?

https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

**Comment by jayp0** [comment]
How to run it as service on Ubuntu, and logging to specific file instead of spamming /var/log/syslog with ticker updated ;)

/etc/systemd/system/gbproxy.service
```
[Unit]
Description=gbproxy

[Service]
# The configuration file application.properties should be here:
WorkingDirectory=/PATH/TO/GunbotProxy
ExecStart=/usr/bin/java -jar GunbotProxyCommunity.jar
Type=simple
User=root
SyslogIdentifier=gbproxy

[Install]
WantedBy=multi-user.target
```

/etc/rsyslog.d/40-gbproxy.conf 
```
if $programname == 'gbproxy' then /var/log/gbproxy.log
& stop
```

/etc/logrotate.d/gbproxy
```
/var/log/gbproxy.log
{
        rotate 7
        missingok
        notifempty
        olddir /var/log/gbproxy
        compress
        delaycompress
        sharedscripts
        postrotate
                invoke-rc.d rsyslog rotate >/dev/null 2>&1 || true
        endscript
}
```

After making these files, run following commands. 
touch /var/log/gbproxy.log
chown syslog /var/log/gbproxy.log
mkdir /var/log/gbproxy
systemctl restart rsyslog
systemctl enable gbproxy.service
systemctl start gbproxy

Now it will start proxy automatically at boot and logs console output to /var/log/gbproxy.log instead of /var/log/syslog
also it will rotate gbproxy.log daily to /var/log/gbproxy/ and keep last 7 logs(compressed).

**Comment by taniman** [comment]
Thank you very much. I created a page for this. Will close the issue now I guess.
https://github.com/taniman/gunbotproxycommunity/wiki/Run-as-a-Service-Ubuntu

**Comment by taniman** [comment]
Hi jayp,

I got a few questions about the service. Could you help me answer them?
https://github.com/taniman/gunbotproxycommunity/issues/18

I will update the wiki page afterwards
