### ISSUE TITLE
Sell only mode

### ISSUE THREAD

**Issue by taniman** [taniman/gunbotproxycommunity#11]
We need a way to tell the proxy we only want to sell

**Comment by jyting** [comment]
Would the plan here to capture any requests that are for a buy order and *not* pass them through the proxy? I.e. at:
`src/main/java/nl/komtek/gpi/controllers/GunbotProxyController.java`

E.g. at the `@RequestMapping(value = "/tradingApi/**", params = "command=buy")` path, it would be some sort of no-op instead of returning the current buy order/buy order with protection?

It could potentially be a 'one-up' over the paid proxy version and allow a 'pair-specific sell-only' mode - probably/possibly using the application settings file.

I'm not very familiar with Spring, but if there's a particular implementation that's decided on for this feature, I'd be happy to give it a go and do a pull request.

**Comment by taniman** [comment]
What do you mean with one-up?

A pair specific sell-only mode would indeed be awesome, but we need then a way to read the properties file while application is running. We would not want to stop/start proxy just to enter sell only mode. 

Maybe start with the initial logic that it needs to be in application.properties and I could enhance it for you? 

Buy your assumption is right. So in the controller, maybe better in the service for the buy method we could just check if the property is there for all_pairs or for a specific pair.
If it is we could return error code and a message saying buying is not allowed.

**Comment by gittygoo** [comment]
Yeah we need this :)
