### ISSUE TITLE
Transparently pass buy/sell orders

### ISSUE THREAD

**Issue by gittygoo** [taniman/gunbotproxycommunity#4]
As requested by another member:

> Hi there! Amazing work with the proxy. I have one question, tough. I was using different Polo accounts, with different APIs, in order to trade ETH and USDT pairs
 Is it possible for the proxy to distinguish between which request came from which Gunbot instance? Because each instance (BTC instance, ETH instance, USDT instance)
 Uses a different API in order to connect with its respective Polo account

A suggestion was: 
Simply not touching buy/sells and use the apis that the pair uses on GB to make those calls.
so the proxy would just mess with the price getting but not the buy/sell

**Comment by taniman** [comment]
Have implemented multi market support. But slightly different, because tranparent pass wasn't working they way I expected. I think because the key's was signed by the bot and then send by the proxy it was not liking that.  So we still need both apiKey and secret. But it seems to work.

If bot A is using key 123, key 345 for ETH trading
define in the properties file
ETH_apiKey1 = 123
ETH_apiSecret1= "your secret"
ETH_apiKey2 = 345
ETH_apiSecret2 = "your other secret"

Although I would suggest using just 1 apiKey for your bots.
Makes setup up the proxy easier.

Bot 1 -> BTC -> 1 trading apiKey
Bot 2 -> ETH -> 1 trading apiKey
Bot 3 -> XMR -> 1 trading apiKey

application.properties

heavy lifting BTC
heavy lifting ETH
heavy lifting XMR

+ 
BTC_apiKey1 + secret same as bot 1
ETH_apiKey1 + secret same as bot 2
XMR_apiKey1 + secret same as bot 3
